#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "ping -c 3 192.168.1.1\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"3 packets transmitted"
}
sleep 1

send --  "firejail\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send -- "firemon --arp\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"192.168.1.1 dev eth0 lladdr"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"REACHABLE"
}
sleep 1

puts "\n"
