#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send --  "firejail --trace firefox\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"1:firefox:open"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"1:firefox:access"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"1:firefox:connect"
}

sleep 1
puts "\n"
