#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send -- "firejail\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send -- "firejail\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Child process initialized"
}
sleep 1

spawn $env(SHELL)
send -- "firejail --cpu\r"
expect {
	timeout {puts "TESTING ERROR 3.1\n";exit}
	"User"
}
expect {
	timeout {puts "TESTING ERROR 3.2\n";exit}
	"System"
}
expect {
	timeout {puts "TESTING ERROR 3.2\n";exit}
	"CPU"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	":firejail"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	":firejail"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	":firejail"
}
sleep 1


puts "\n"

