#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --debug --profile=test2.profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Processing line #caps#"
}
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"Processing line #seccomp#"
}
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"Processing line #private#"
}
expect {
	timeout {puts "TESTING ERROR 2.1\n";exit}
	"Reading test.profile"
}
expect {
	timeout {puts "TESTING ERROR 2.2\n";exit}
	"Processing line #blacklist /bin/rmdir#"
}
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"Mounting a new /home directory"
}
expect {
	timeout {puts "TESTING ERROR 4\n";exit}
	"Drop CAP_SYS_MODULE"
}
expect {
	timeout {puts "TESTING ERROR 5\n";exit}
	"Initialize seccomp filter"
}
expect {
	timeout {puts "TESTING ERROR 6\n";exit}
	"Blacklisting syscall mount"
}
expect {
	timeout {puts "TESTING ERROR 7\n";exit}
	"Child process initialized"
}

sleep 1
puts "\n"
