#!/usr/bin/expect -f

set timeout 10
spawn $env(SHELL)
match_max 100000

send -- "firejail --profile=test.profile\r"
expect {
	timeout {puts "TESTING ERROR 0\n";exit}
	"Child process initialized"
}

sleep 2
send -- "ls /sbin\r"
expect {
	timeout {puts "TESTING ERROR 1\n";exit}
	"cannot open"
}

sleep 1
send -- "ls /usr/sbin\r"
expect {
	timeout {puts "TESTING ERROR 2\n";exit}
	"cannot open"
}

sleep 1
send -- "ls -l /etc/shadow\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"root root 0"
}

sleep 1
send -- "ls -l /bin/rmdir\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"root root 0"
}

sleep 1
send -- "ls -l /bin/mount\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"root root 0"
}

sleep 1
send -- "ls -l /bin/umount\r"
expect {
	timeout {puts "TESTING ERROR 3\n";exit}
	"root root 0"
}

sleep 1
puts "\n"
