#include "firejail.h"

void usage(void) {
	printf("firejail - version %s\n\n", VERSION);
	printf("Firejail is a sandbox program that reduces the risk of security breaches by\n");
	printf("restricting the running environment of untrusted applications using Linux\n");
	printf("namespaces. It currently implements hostname, filesystem, PID, IPC and\n");
	printf("networking stack isolation, and it runs on any recent Linux system. It includes\n");
	printf("a sandbox profile for Mozilla Firefox.\n\n");
	printf("Usage: firejail [options] [program and arguments]\n\n");
	printf("Options:\n");
	printf("\t-c - execute command and exit\n");
	printf("\t--chroot=dirname - chroot into dirname directory\n");
	printf("\t--debug - print sandbox debug messages\n");
	printf("\t--help, -? - this help screen\n");
	printf("\t--ip=ipaddress - use this IP address in the new network namespace\n");
	printf("\t--join=pid - join the sandbox of the specified process\n");
	printf("\t--name=name - set sandbox hostname\n");
	printf("\t--net=bridgename - enable network namespaces and connect to this bridge\n");
	printf("\t\tdevice\n");
	printf("\t--net=none - enable a new, unconnected network namespace\n");
	printf("\t--private - mount a new /home/user directory\n");
	printf("\t--profile=filename - use a custom profile\n");
	printf("\t--version - print program version and exit\n");
	printf("\n");
	printf("The profile files define a chroot filesystem built on top of the existing\n");
	printf("filesystem. Each line describes a file element that is removed from\n");
	printf("the filesystem, for example:\n");
	printf("\n");
	printf("# this is a comment\n");
	printf("blacklist /etc/password # remove /etc/password file\n");
	printf("blacklist /usr/bin # remove /usr/bin directory\n");
	printf("blacklist /usr/bin/gcc* # remove all gcc files in /usr/bin (file globbing)\n");
	printf("blacklist ${PATH}/ifconfig # remove ifconfig from the regular path directories\n");
	printf("blacklist ${HOME}/.ssh # remove .ssh directory from user home directory\n");
	printf("\n");
	printf("Default Firejail profile files are placed in /etc/firejail directory, user\n");
	printf("profile files are placed in ~/.config/firejail directory. \n\n");
	printf("Examples:\n\n");
	printf("   $ firejail\n");
	printf("          start a regular /bin/bash session in sandbox\n");
	printf("   $ firejail firefox\n");
	printf("          start Mozilla Firefox\n");
	printf("   $ firejail --debug firefox\n");
	printf("          debug Firefox sandbox\n");
	printf("   $ firejail --private\n");
	printf("          start a /bin/bash session with a new tmpfs home directory\n");
	printf("   $ firejail --net=br0 ip=10.10.20.10\n");
	printf("          start a /bin/bash session in a new network namespace; the session is\n");
	printf("          connected to the main network using br0 bridge device, an IP address\n");
	printf("          of 10.10.20.10 is assigned to the sandbox\n");
	printf("   $ firejail --list\n");
	printf("          list all running sandboxes\n");
	printf("\n");
	printf("Copyright\n");
	printf("   Copyright @ 2014 netblue30@yahoo.com\n");
	printf("   License GPL version 2 or later\n");
	printf("   Homepage: http://firejail.sourceforge.net\n");
	printf("\n");
}
